<?php

use Illuminate\Database\Seeder;

class PcCuentaauxiliarTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pc_cuentaauxiliar')->delete();
        
        \DB::table('pc_cuentaauxiliar')->insert(array (
            0 => 
            array (
                'id' => 1,
                'codigo' => '15040505',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2175,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'codigo' => '15040510',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2175,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'codigo' => '15040599',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2175,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'codigo' => '15041005',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2176,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'codigo' => '15041010',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2176,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'codigo' => '15041015',
            'nombre' => 'Depreciación (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2176,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'codigo' => '15040599',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2175,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'codigo' => '15240505',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2195,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'codigo' => '15240510',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2195,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'codigo' => '15240515',
            'nombre' => 'Depreciación (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2195,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'codigo' => '15240599',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2195,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'codigo' => '15241005',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2196,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'codigo' => '15241010',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2196,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'codigo' => '15241015',
            'nombre' => 'Depreciación (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2196,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'codigo' => '15241099',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2196,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'codigo' => '15400505',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2201,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'codigo' => '15400510',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2201,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'codigo' => '15400515',
            'nombre' => 'Depreciación Acumulada (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2201,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'codigo' => '15400599',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2201,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'codigo' => '15401005',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2202,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'codigo' => '15401010',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2202,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'codigo' => '15401015',
            'nombre' => 'Depreciación Acumulada (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2202,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'codigo' => '15401099',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2202,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'codigo' => '15401505',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2203,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'codigo' => '15401510',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2203,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'codigo' => '15401515',
            'nombre' => 'Depreciación Acumulada (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2203,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'codigo' => '15401599',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2203,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'codigo' => '16100505',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2215,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'codigo' => '16100510',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2215,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'codigo' => '16100515',
            'nombre' => 'Amortización Acumulada (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2215,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'codigo' => '16100599',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2215,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'codigo' => '16101005',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2216,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'codigo' => '16101010',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2216,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'codigo' => '16101015',
            'nombre' => 'Amortización Acumulada (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2216,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'codigo' => '16101099',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2216,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'codigo' => '16101505',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2217,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'codigo' => '16101510',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2217,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'codigo' => '16101515',
            'nombre' => 'Amortización Acumulada (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2217,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'codigo' => '16101599',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2217,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'codigo' => '16102005',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2218,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'codigo' => '16102010',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2218,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'codigo' => '16102015',
            'nombre' => 'Amortización Acumulada (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2218,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'codigo' => '16102099',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2218,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'codigo' => '16102505',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2219,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'codigo' => '16102510',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2219,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'codigo' => '16102515',
            'nombre' => 'Amortización Acumulada (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2219,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'codigo' => '16102599',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2219,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'codigo' => '16103005',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2220,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'codigo' => '16103010',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2220,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'codigo' => '16103015',
            'nombre' => 'Amortización Acumulada (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2220,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'codigo' => '16103099',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2220,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'codigo' => '16103505',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2221,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'codigo' => '16103510',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2221,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'codigo' => '16103515',
            'nombre' => 'Amortización Acumulada (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2221,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'codigo' => '16103599',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2221,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'codigo' => '16104005',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2222,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'codigo' => '16104010',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2222,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'codigo' => '16104015',
            'nombre' => 'Amortización Acumulada (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2222,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'codigo' => '16104099',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2222,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'codigo' => '16104505',
                'nombre' => 'Modelo de Costo',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2223,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'codigo' => '16104510',
                'nombre' => 'Modelo de Revaluación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2223,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'codigo' => '16104515',
            'nombre' => 'Amortización Acumulada (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2223,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'codigo' => '16104599',
            'nombre' => 'Deterioro (Cr)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2223,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'codigo' => '21060505',
                'nombre' => 'Aceptaciones Bancarias',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'codigo' => '21060520',
                'nombre' => 'Contratos de Forward - Especulación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'codigo' => '21060525',
                'nombre' => 'Contratos de Forward - cobertura',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'codigo' => '21060530',
                'nombre' => 'Contratos de Futuros - Especulación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'codigo' => '21060535',
                'nombre' => 'Contratos de Futuros - cobertura',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'codigo' => '21060540',
                'nombre' => 'Swaps – Especulación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'codigo' => '21060545',
                'nombre' => 'Swaps – cobertura',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'codigo' => '21060550',
                'nombre' => 'Opciones –Especulación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'codigo' => '21060555',
                'nombre' => 'Opciones –cobertura',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'codigo' => '21060505',
                'nombre' => 'Aceptaciones Bancarias',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'codigo' => '21060520',
                'nombre' => 'Contratos de Forward - Especulación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'codigo' => '21060525',
                'nombre' => 'Contratos de Forward - cobertura',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'codigo' => '21060530',
                'nombre' => 'Contratos de Futuros - Especulación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'codigo' => '21060535',
                'nombre' => 'Contratos de Futuros - cobertura',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'codigo' => '21060540',
                'nombre' => 'Swaps – Especulación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'codigo' => '21060545',
                'nombre' => 'Swaps – cobertura',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'codigo' => '21060550',
                'nombre' => 'Opciones –Especulación',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'codigo' => '21060555',
                'nombre' => 'Opciones –cobertura',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2287,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'codigo' => '24040501',
                'nombre' => 'Vigencia fiscal corriente',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2332,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'codigo' => '24040502',
                'nombre' => 'Vigencias fiscales anteriores',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2332,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'codigo' => '24051001',
                'nombre' => 'Salarios y pagos laborales',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2333,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'codigo' => '24051002',
                'nombre' => 'Honorarios',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2333,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'codigo' => '24051003',
                'nombre' => 'Comisiones',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2333,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'codigo' => '24051004',
                'nombre' => 'Servicios',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2333,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'codigo' => '24051005',
                'nombre' => 'Arrendamientos',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2333,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'codigo' => '24051006',
                'nombre' => 'Rendimientos financieros',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2333,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'codigo' => '24051007',
                'nombre' => 'Compras',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2333,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'codigo' => '24051008',
                'nombre' => 'Por pagos al exterior',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2333,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'codigo' => '24051009',
                'nombre' => 'Por impuesto de timbre',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2333,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'codigo' => '24051010',
                'nombre' => 'Autorretenciones',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2333,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'codigo' => '24051011',
                'nombre' => 'Retención cree',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2333,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'codigo' => '24051012',
                'nombre' => 'Pago retención en la fuente',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2333,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'codigo' => '24100501',
                'nombre' => 'Venta de bienes',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2334,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'codigo' => '24100502',
                'nombre' => 'Venta de servicios',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2334,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'codigo' => '24100503',
                'nombre' => 'Devoluciones en compra de bienes',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2334,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'codigo' => '24100504',
                'nombre' => 'Devoluciones en compra de servicios',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2334,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'codigo' => '24100505',
            'nombre' => 'Compra de bienes (DB)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2334,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'codigo' => '24100506',
            'nombre' => 'Compra de servicios (DB)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2334,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'codigo' => '24100507',
            'nombre' => 'Devoluciones en venta de bienes (DB)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2334,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'codigo' => '24100508',
            'nombre' => 'Devoluciones en venta de servicios (DB)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2334,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'codigo' => '24100575',
            'nombre' => 'Impuesto a las ventas retenido (DB)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2334,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'codigo' => '24100580',
            'nombre' => 'Valor pagado (DB)',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2334,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'codigo' => '24101004',
                'nombre' => 'Vigencia actual por pagar',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2335,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'codigo' => '24101005',
                'nombre' => 'Impuesto de industria y comercio retenido Bogotá',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2335,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'codigo' => '24101006',
                'nombre' => 'Impuesto de industria y comercio retenido Samacá',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2335,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'codigo' => '24101010',
                'nombre' => 'Impuesto de industria y comercio retenido Sutatausa',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2335,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'codigo' => '24101015',
                'nombre' => 'Impuesto de industria y comercio retenido Soacha',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2335,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'codigo' => '24101503',
                'nombre' => 'Predial unificado',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2336,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'codigo' => '24101505',
                'nombre' => 'Valorización',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2336,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'codigo' => '24101509',
                'nombre' => 'Registro',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2336,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'codigo' => '24101514',
                'nombre' => 'Cuotas de fiscalización y auditaje',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2336,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'codigo' => '24101516',
                'nombre' => 'Impuesto sobre vehículos automotores',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2336,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'codigo' => '24101522',
                'nombre' => 'Impuesto al patrimonio',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2336,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'codigo' => '24101527',
                'nombre' => 'Impuestos, contribuciones y tasas en el exterior',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2336,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'codigo' => '24101580',
                'nombre' => 'Otros impuestos departamentales',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2336,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'codigo' => '24101585',
                'nombre' => 'Otros impuestos municipales',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2336,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'codigo' => '24101590',
                'nombre' => 'Otros impuestos distritales',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2336,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'codigo' => '24101595',
                'nombre' => 'Multas y sanciones',
                'descripcion' => 'NN',
                'ajuste' => 'NN',
                'tercero_activo' => false,
                'estado' => false,
                'subcuenta_id' => 2336,
                'tipo' => 'NIIF',
                'created_at' => '0001-01-01 00:00:00',
                'updated_at' => '0001-01-01 00:00:00',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}
